sudo: required
language: node_js
node_js:
  - '9'
services:
  - docker
branches:
  only:
    - master
    - "/v\\d+\\.\\d+\\.\\d+(-\\w+)?/"
stages:
  - test
  - build
  - deploy
jobs:
  include:
    - stage: test
      if: tag IS present
      install: skip
      script:
      - npm run test-with-coverage
    - stage: build
      if: tag IS present
      install: skip
      script:
      - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
      - docker build --tag pyrrha_boxproxy .
      - docker images
      - docker tag pyrrha_boxproxy pandoraboxchain/pyrrha_boxproxy:latest
      - docker push pandoraboxchain/pyrrha_boxproxy:latest
    - stage: deploy
      if: tag IS present
      install: skip
      script:
      - openssl aes-256-cbc -K $encrypted_9c3be0b76b35_key -iv $encrypted_9c3be0b76b35_iv -in ./key.enc -out ./key -d
      - chmod 600 ./key
      - sed -i 's/\$SERVER_PASSWORD/'"$SERVER_PASSWORD"'/g' ./deploy.sh
      - ssh -o "StrictHostKeyChecking no" -i ./key kostysh@pandora.network 'bash -s' < ./deploy.sh
