sudo: required
language: node_js
node_js:
  - '9'
services:
  - docker
stages:
 - test
 - build
 - deploy
jobs:
  include:
    - stage: test
      if: branch = master AND tag IS present
      install: skip
      script:
      - npm run test-with-coverage
    - stage: build
      if: branch = master AND tag IS present
      install: skip
      script:
      - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
      - docker build --tag pyrrha_boxproxy .
      - docker images
      - docker tag pyrrha_boxproxy pandoraboxchain/pyrrha_boxproxy:latest
      - docker push pandoraboxchain/pyrrha_boxproxy:latest
    - stage: deploy
      if: branch = master AND tag IS present
      install: skip
      script:
      - openssl aes-256-cbc -K $encrypted_9c3be0b76b35_key -iv $encrypted_9c3be0b76b35_iv -in ./tests/key.enc -out ./tests/key -d
      - ssh -o "StrictHostKeyChecking no" -i ./tests/key pandora.network
      - echo $SERVER_PASSWORD | sudo su
      - cd /home/orlovsky/pyrrha
      - git reset --hard
      - git pull
      - cd /home/orlovsky/pyrrha/containers
      - docker-compose pull
      - docker-compose down
      - docker-compose up -d
      - exit
