sudo: required

language: node_js
node_js:
  - "9"

services:
  - docker
  
jobs:
  include:
    - stage: test master
      if: branch = master
      script:
        - npm run test-with-coverage

    - stage: build docker image
      if: (branch = master) AND (tag IS present)
      script:
        - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
        - docker build --tag pyrrha_boxproxy .
        - docker images
        - docker tag pyrrha_boxproxy pandoraboxchain/pyrrha_boxproxy:latest
        - docker push pandoraboxchain/pyrrha_boxproxy:latest


