version: "2"
services:

  pyrrha_boxproxy:
    container_name: "pyrrha_boxproxy"
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      - WEB3_PROTOCOL=ws
      - WEB3_HOSTNAME=node.rsk.pandora.network
      - WEB3_PORT=4445
      - PAN_ADDRESS=0xcdca0f85f696a8a8d70a6ecd74236690548bf44b
      - MARKET_ADDRESS=0x55da07dbb7c76cb6be03f6ab6669626a83ec250d
    ports:
      - "1112:1111"
      - "1338:1337"
    volumes:
      - "./tmp:/logs"
    networks: 
      main:
        aliases:
          - pyrrha_boxproxy    

networks: 
  main:
