version: "2"
services:

  pyrrha_boxproxy:
    container_name: "pyrrha_boxproxy"
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      - WEB3_PROTOCOL=ws
      - WEB3_HOSTNAME=rinkeby.pandora.network
      - WEB3_PORT=8546
      - PAN_ADDRESS=0xa04dbdd6114ec21ec75629f6cc2c582bd78bb007
      - MARKET_ADDRESS=0x08b3e1813a8da52e61239d048183e2fb862ded5d
    ports:
      - "1111:1111"
      - "1337:1337"
    volumes:
      - "./tmp:/logs"
    networks: 
      main:
        aliases:
          - pyrrha_boxproxy    

networks: 
  main:
