version: "2"
services:

  pyrrha_boxproxy:
    container_name: "pyrrha_boxproxy"
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      - WEB3_PROTOCOL=ws
      - WEB3_HOSTNAME=rinkeby.pandora.network
      - WEB3_PORT=8546
      - PAN_ADDRESS=0xa40600efcb9b69003757fb196304858f989888a1
      - PANDORA_ADDRESS=0x2ac8d321cdfdc1fa5591a38ee2c2bcbe094b64d7
      - ECONOMIC_ADDRESS=0x3c2f60a3c1dba316c1031925712339f694f0da99
      - MARKET_ADDRESS=0xfd4158c461df6295229e23c7686f8684a0d26531
    ports:
      - "1111:1111"
      - "1337:1337"
    volumes:
      - "./tmp:/logs"
    networks: 
      main:
        aliases:
          - pyrrha_boxproxy    

networks: 
  main:
