version: "2"
services:

  pyrrha_boxproxy:
    container_name: "pyrrha_boxproxy"
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      - WEB3_PROTOCOL=ws
      - WEB3_HOSTNAME=rinkeby.pandora.network
      - WEB3_PORT=8546
      - PAN_ADDRESS=0xf23f45caa5c697c54d2e92ecbee48855233040e1
      - MARKET_ADDRESS=0xd1feab2687c6beea17d8c1f728aaf54aed5c0ea9
    ports:
      - "1111:1111"
      - "1337:1337"
    volumes:
      - "./tmp:/logs"
    networks: 
      main:
        aliases:
          - pyrrha_boxproxy    

networks: 
  main:
