version: "2"
services:

  pyrrha_boxproxy:
    container_name: "pyrrha_boxproxy"
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      - WEB3_PROTOCOL=https
      - WEB3_HOSTNAME=ropsten.infura.io/Llc2pOEtpgzvopBH8dst
      - WEB3_PORT=
      - PAN_ADDRESS=0xb1746daa5260ba5d94c6b407b226b1cb190190ab
    ports:
      - "1111:1111"
    volumes:
      - "./tmp:/logs"
    networks: 
      main:
        aliases:
          - pyrrha_boxproxy    

networks: 
  main:
