version: "2"
services:

  pyrrha_boxproxy:
    container_name: "pyrrha_boxproxy"
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      - WEB3_PROTOCOL=http
      - WEB3_HOSTNAME=dockstation.pandora.network
      - WEB3_PORT=8545
      - PAN_ADDRESS=0x58e66b79928cfb362b53c185a6a1fded882bb07d
    ports:
      - "1111:1111"
    volumes:
      - "./tmp:/logs"
    networks: 
      main:
        aliases:
          - pyrrha_boxproxy    

networks: 
  main:
