version: "2"
services:

  pyrrha_boxproxy:
    container_name: "pyrrha_boxproxy"
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      - WEB3_HOSTNAME=172.17.0.1
      - PAN_ADDRESS=0x2c2b9c9a4a25e24b174f26114e8926a9f2128fe4
    ports:
      - "1111:1111"
      - "1337:1337"
      - "5858:5858"
    volumes:
      - "./tmp:/logs"
    networks: 
      main:
        aliases:
          - pyrrha_boxproxy    

networks: 
  main:
