version: "2"
services:

  pyrrha_boxproxy:
    container_name: "pyrrha_boxproxy"
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      - WEB3_PROTOCOL=wss
      - WEB3_HOSTNAME=rinkeby.infura.io/ws
      - WEB3_PORT=8546
      - PAN_ADDRESS=0x853be7e8af1686893648cf34117c618f9eae56ea
      - MARKET_ADDRESS=0x3da170350158dd0ad191ce5c193562d49a0203cd
    ports:
      - "1111:1111"
      - "1337:1337"
    volumes:
      - "./tmp:/logs"
    networks: 
      main:
        aliases:
          - pyrrha_boxproxy    

networks: 
  main:
